spring.application.name=currencyJournal

sync.enabled=false
sync.interval.seconds=3600


# connect to PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/currencyJournal
spring.datasource.username=user
spring.datasource.password=123

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

cbr.api.url=https://www.cbr-xml-daily.ru/daily_utf8.xml

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

spring.jpa.show-sql=true