spring.application.name=currencyJournal

# connect to PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/currencyJournal
spring.datasource.username=user
spring.datasource.password=123

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# only for develop time
spring.jpa.show-sql=true